### PR TITLE
79 company info page jasmine

### PR DESCRIPTION
**Pull request by jmm28**
I've created the forms for the company info page (the main view, a form to create a new company, and a page that can view/edit a particular company's information). I started a company_info.py page for the company info routes, but it's not 100% functional yet on the back-end part.

### CODE REVIEW

**Comment by jmm28** [comment]
> 1. The states section shouldn't be an option to choose pre-loaded states.  This locks us into a USA only app.  State/Province will work fine and the user can input whatever.  We haven't built out a large database that handles many nations and states yet.  So let's keep it simple.
> 2. I don't think it is necessary to create a company routes .py file.  It would be more logical to create a profile.py file and move all company and user profile routes into that.
> 3. in your company info py file, you are declaring a new flask app.  Don't do that.  We create one in init.py and we create the app.
> 4. Let's make those changes and get the back-end working and I'll review again.

Thank you for your review! I'll leave all of the input fields as generic text fields for now. Also, I had some issues with testing the routes, which is why there is a new flask app declared (I was trying different band-aids...); I forgot to delete it. 

Thanks again! I'll get those changes up.

**Comment by stuart909** [comment]
> > 1. The states section shouldn't be an option to choose pre-loaded states.  This locks us into a USA only app.  State/Province will work fine and the user can input whatever.  We haven't built out a large database that handles many nations and states yet.  So let's keep it simple.
> > 2. I don't think it is necessary to create a company routes .py file.  It would be more logical to create a profile.py file and move all company and user profile routes into that.
> > 3. in your company info py file, you are declaring a new flask app.  Don't do that.  We create one in init.py and we create the app.
> > 4. Let's make those changes and get the back-end working and I'll review again.
> 
> Thank you for your review! I'll leave all of the input fields as generic text fields for now. Also, I had some issues with testing the routes, which is why there is a new flask app declared (I was trying different band-aids...); I forgot to delete it.
> 
> Thanks again! I'll get those changes up.

Just FYI, 

`from flask import current_app`

This will contain all of our configured blueprints and configs.

**Comment by jmm28** [comment]
I've implemented the following changes:
1. I deleted the company_info.py routes page and created a profiles.py routes page that contains the profile-related and company-related routes. Right now, they use two Blueprints (one for profile info and one for company info). 
2. I reverted the State input field to a regular text input.

**Comment by jmm28** [comment]
I've merged Kartik's back-end changes into this branch.

**Review by stuart909 — APPROVED** [review]

**Pull request merged**
