### PR TITLE
85 create forum post form andy fix

### PR DESCRIPTION
**Pull request by achen236**
The sqlalchemy error still occurs on my end, but commenting out Forum_Post's comment key allows the server to run, so I was able to test create post functionality and fix some broken urls and dates. Also ordered posts by most recent.

Screen Shot 2022-07-27 at 2 29 31 PM

### CODE REVIEW

**Comment by stuart909** [comment]
I'll pull this down and fix it.

**Comment by stuart909** [comment]
I am roping in Jasmine and Kartik.  Then I just realized this is a pull request.  I am going to kill this request, let me explain.

There are good and bad things with this design.  Let's simplify your design a bit and we can break it down into parts.  I don't like the posts going under the new forum post form screen after all.  Also, I think you need to compartmentalize a bit more.  Remember, you can create mini forms that extend other mini parts of a page that extends a main part of a page.  These things become dynamic and easily swappable.  What I see here is that you are trying to do everything on one screen instead of creating many independent mini views (jinja templates), that can be dynamically loaded in when we click buttons.

Let's draw up something and put out a file plan for how we can handle this view.  I think the functional code is mostly there, but the lack of breaking this page up into a bunch of parts is setting you back.

**Comment by achen236** [comment]
I agree the code should be broken down and I will work on that.

> I don't like the posts going under the new forum post form screen after all. 

Did you want the new forum post form to be on a different page than the forum posts? Where you would click a button "Create post" and it'll load a new page: /forums/<int:thread>/create_post/ with the create new post form?

**Comment by achen236** [comment]
I tried to compartmentalize the code a bit. I created a forums folder and a forums.py. I also created a new page for the create post form and added tags to the form because I somehow forgot before. Is this what you had in mind?

Screen Shot 2022-07-28 at 6 30 36 PM

Screen Shot 2022-07-28 at 6 30 10 PM

**Comment by stuart909** [comment]
I think we need to put the forum posts into a form or div.  Then put the create post button on the bottom:

image

**Comment by achen236** [comment]
Like this?
Screen Shot 2022-07-29 at 3 54 26 PM

**Comment by stuart909** [comment]
Yes.  But now you need to create a div for the threadID and loop through the first 5 or so newest posts in that thread in the folder like this:

image

**Comment by stuart909** [comment]
You iterate through thread first and fill out the posts in the thread and go down the line.  Maybe first 10 threads?

**Review by stuart909 — CHANGES_REQUESTED** [review]
see images and commentary above

**Comment by achen236** [comment]
I've created the thread div, but I'm not sure how you want to new create threads. Currently when you create a post it adds it to the 'home' thread which is the default.

Screen Shot 2022-08-01 at 3 30 32 PM

**Pull request closed without merging**
