### PR TITLE
add text to home file

### PR DESCRIPTION
**Pull request by imamyy**
Hi, could you please review my change? 
P/s: This is a demo of how to set up peer reviews in our project.

### CODE REVIEW

**Review by stuart909 — CHANGES_REQUESTED** [review]
I am not sure what I am reviewing, save that this is a demo.  There are 1631 files committed and I don't see any commentary.  I am aware this is a demo pull request, so if this were a real pull request, I would have to reject it because I have no idea why it was made, or what the requester was hoping to accomplish by adding a large amount of source files in a request.

Typically, we would want to promote smaller pull requests where I only have to review a small amount of changes.  I will send a screen shot of what I am seeing.

**Comment by stuart909** [comment]
image

**Comment by stuart909** [comment]
> image

This is essentially a new repo.  You wrote a hello.py software and included a user environment.  We typically don't want to push the source files because we can submit a config file that can be run and the user will download the requirements if they don't have them.  This saves space on our github server.

**Comment by imamyy** [comment]
I apologize for the huge amount of code posted here. I have just closed the pull request. I am not farmiliar with GitHub yet, so I made a mistake. Thank you for your comments.

**Comment by kiserd** [comment]
> I apologize for the huge amount of code posted here. I have just closed the pull request. I am not farmiliar with GitHub yet, so I made a mistake. Thank you for your comments.



> I apologize for the huge amount of code posted here. I have just closed the pull request. I am not farmiliar with GitHub yet, so I made a mistake. Thank you for your comments.

@imamyy 
If you ever have any questions, you can shoot them my way. I'm still a Git/GH newbie, but I've been using it for a couple years. We could also setup a meeting sometime if you'd like. Just let me know :)

**Comment by ziniwang** [comment]
> I apologize for the huge amount of code posted here. I have just closed the pull request. I am not farmiliar with GitHub yet, so I made a mistake. Thank you for your comments.

Amy, you did a great job for taking a step forward, at least ahead of me. So no need to apologize. I'm also new to GitHub and being very confused now. Could we setup a meeting and discuss how it works together?

**Comment by stuart909** [comment]
> I apologize for the huge amount of code posted here. I have just closed the pull request. I am not farmiliar with GitHub yet, so I made a mistake. Thank you for your comments.

Don't worry.  I was being verbose so we can write up better documentation and onboard our people better.  I am happy you are working these issues and hopefully we can create better documentation together and help everyone :)

**Pull request closed without merging**
