### PR TITLE
75 edit passwords needs to function andy

### PR DESCRIPTION
**Pull request by achen236**
Edit password with error handling when current password is incorrect, or when new password and new confirmation password don't match. 
Screen Shot 2022-07-15 at 4 15 44 PM
Screen Shot 2022-07-15 at 4 16 25 PM
Screen Shot 2022-07-15 at 4 16 04 PM

### CODE REVIEW

**Review by stuart909 — CHANGES_REQUESTED** [review]
You need to split this task up into multiple functions that are run in with blocks.  It is more secure to make use of a with block when you evaluate the form and check the passwords.  We need to be absolutely sure that we are pulling the correct user first and checking if the supplied password is correct.  If this is true, then we move into another with block and test our passwords.

1. Check user's password supplied in the current password is correct, return boolean
2. If 1 is good (use decorator on 2 function) then we run two, which checks our passwords supplied match.  Return boolean
3. Function 3 is wrapped with function 2 boolean.  If function 2 is true, function 3 executes and sets the password in the data base.

Currently, I am seeing very strange behavior and my account either gets locked out or the password says there is a problem but the password no longer works.  The back-end is borked.

**Comment by stuart909** [comment]
I am bringing in Kartik to assist

**Comment by achen236** [comment]
I believe the strange behavior was due to using an if statement instead of an elif statement causing the password to be changed even if the current password entered was incorrect. I have fixed that, but I will continue to attempt to implement this task in the way you described.

**Comment by stuart909** [comment]
> 

That's fine.  Do your best to make it function and I will duct tape it in main in a patch later

**Comment by stuart909** [comment]
If you got it functional, are you ready for me to review it again?

**Comment by achen236** [comment]
Yes, it's ready to be reviewed.

**Pull request merged**
