### PR TITLE
admin view

### PR DESCRIPTION
**Pull request by stuart909**

### CODE REVIEW

**Comment by stuart909** [comment]
Logan / Kartik,

can one of you do me a favor and close this pull request and initiate a pull request from 39-blogposts -> kartik_blogposts?  Just like this.  I cannot assign myself as reviewer because I requested it.

**Comment by kiserd** [comment]
> Logan / Kartik,
> 
> can one of you do me a favor and close this pull request and initiate a pull request from 39-blogposts -> kartik_blogposts? Just like this. I cannot assign myself as reviewer because I requested it.

Just to confirm. You want me to create an exact replica of this PR merging `kartik_blogpost` -> `39-blogposts`?

Would you like me to `rm` the pycache and virtual env stuff first?

**Comment by stuart909** [comment]
> > Logan / Kartik,
> > can one of you do me a favor and close this pull request and initiate a pull request from 39-blogposts -> kartik_blogposts? Just like this. I cannot assign myself as reviewer because I requested it.
> 
> Just to confirm. You want me to create an exact replica of this PR merging `kartik_blogpost` -> `39-blogposts`?
> 
> Would you like me to `rm` the pycache and virtual env stuff first?

yes and yes

**Comment by stuart909** [comment]
also, would the both of you go over how to do the pull requests in this manner?  I would like everyone spreading the word to create pull requests and ensure everyone is doing work and submitting changes to an issue branch by submitting pull requests.

**Comment by kiserd** [comment]
Closing PR per Stuart's request. Will open an identical PR immediately.

**Pull request closed without merging**
