### PR TITLE
88 new comment form ye

### PR DESCRIPTION
**Pull request by yeaung00**
I created the front end view that allows users to reply to a forum post with a comment. This feature does not append the comments to the forum post.

Screen Shot 2022-07-21 at 4 12 44 PM

Screen Shot 2022-07-21 at 4 13 52 PM

Screen Shot 2022-07-21 at 4 14 15 PM

User must sign in to comment.

### CODE REVIEW

**Comment by jmm28** [comment]
Ye and I talked about getting the comments displayed on a post. On the back-end, what does the forum model look like? Is there a comments field for a post that we can append a comment to? In that case, we can grab a post's comment list and display each comment in a for-loop. 

(Though it's possible that it's much simpler than how I'm currently seeing it.)

**Comment by stuart909** [comment]
Good progress so far, but we should really create some divs to control the form section for making a comment and the form for rendering comments.  I wouldn't make the comment box INSIDE the forum post.  Typically, the forum post would have it's own box/form combo, and comments would be comment box/forms that append below it.

**Comment by stuart909** [comment]
image

**Comment by stuart909** [comment]
image

**Comment by stuart909** [comment]
image

**Comment by yeaung00** [comment]
I've encapsulated each form with their own divs. However, I'm not sure how to replace the example posts with the forum model and append the comments to the database. How should I approach this issue?

**Comment by stuart909** [comment]
Let's work this in the issue and not a pull request.

**Pull request closed without merging**
