### PR TITLE
85 create forum post form andy

### PR DESCRIPTION
**Pull request by achen236**
I created a create forum post form. The form is only viewable if you are signed in. 

Screen Shot 2022-07-21 at 3 09 51 PM

Screen Shot 2022-07-21 at 3 12 26 PM

I also added an `id` url variable in the forums route. Based on the forum `id`, the form includes it as a hidden input, so the backend knows which forum to create the post in. The route /forums  with no `id`, also now routes to a default forum which is currently `id=1`.

### CODE REVIEW

**Comment by stuart909** [comment]
Let's get rid of the example posts.  We don't need them anymore.  The original intern, Serj, created them just as a quick example.  I'm surprised they have lasted so long :P

**Review by stuart909 — CHANGES_REQUESTED** [review]
Get rid of the example posts.  Let's delete the declared dictionary and just use things out of our database.  Do that and I will feel more confident to approve this merge when you think the task is done.

**Comment by achen236** [comment]
I have got rid of the dummy variables and tried to merge the forum models.py from 91-data-model-forum-comment branch so I can use the database , but it is broken and I'm not sure what the problem is.

**Comment by stuart909** [comment]
I'll take another look in the morning

**Pull request merged**
